backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/
public_folder: /
logo_url: https://estep.nyc/logo/full-logo.svg
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "page"
    extension: "mdx"
    format: frontmatter
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    slug: "{{permalink}}"
    media_folder: ""
    public_folder: ""
    summary: "{{title}} ({{permalink}})"
    sortableFields: ["title", "permalink", "date"]
    preview_path: "{{permalink}}"
    fields:
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    extension: mdx
    format: frontmatter
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}/{{month}}/{{title}}/index"
    media_folder: ""
    public_folder: ""
    preview_path: "blog/{{year}}/{{month}}/{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Display size",
          name: "size",
          widget: "select",
          default: "small",
          multiple: false,
          options: ["normal", "small"],
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    extension: mdx
    format: frontmatter
    label: "Projects"
    label_singular: "Project"
    folder: "src/content/projects"
    create: true
    slug: "{{title}}/index"
    media_folder: ""
    public_folder: ""
    preview_path: "projects/{{title}}"
    sortableFields: ["title", "date", "size"]
    view_filters:
      - label: "JavaScript"
        field: languages
        pattern: "javascript"
      - label: "TypeScript"
        field: languages
        pattern: "typescript"
      - label: "Has banner"
        field: banners
        pattern: true
      - label: "Small"
        field: size
        pattern: "small"
      - label: "Normal"
        field: size
        pattern: "normal"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - {
          label: "Display size",
          name: "size",
          widget: "select",
          default: "normal",
          multiple: false,
          options: ["normal", "small"],
          required: true,
        }
      - { label: "Publish Date", name: "date", widget: "date", required: true }
      - {
          label: "Banners",
          name: "banners",
          widget: "select",
          options: ["hackathon"],
          multiple: true,
          required: false,
        }
      - {
          label: "Technologies Used",
          name: "tech",
          widget: "select",
          required: true,
          multiple: true,
          options:
            [
              "python",
              "node",
              "express",
              "javascript",
              "typescript",
              "angular",
              "react",
              "nextjs",
              "gatsby",
              "graphql",
              "react-native",
              "redux",
              "electron",
              "postgres",
              "mongodb",
              "redis",
              "firebase",
              "styled-components",
              "sass",
              "theme-ui",
              "feathers",
              "mobx-state-tree",
              "css3",
              "html5",
              "heroku",
              "aws",
              "azure",
              "netlify",
              "parse",
              "sequelize",
              "serverless",
              "mongoose",
              "docker",
              "socketio",
            ],
        }
      - {
          label: "Languages",
          name: "languages",
          widget: "select",
          multiple: true,
          required: true,
          options: ["javascript", "typescript", "python"],
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: Image, name: image, widget: "file" },
        }
      - { label: "Git Repository URL", name: "repo", widget: "string" }
  - name: "work"
    label: "Work Experience"
    folder: "src/content/work"
    extension: mdx
    format: frontmatter
    create: false
    slug: "{{companyName}}-{{position}}"
    media_folder: ""
    public_folder: ""
    identifier_field: companyName
    summary: "{{position}} @ {{companyName}} ({{startDate}} - {{endDate}})"
    sortableFields: ["companyName", "position", "startDate", "endDate"]
    view_filters:
      - label: "Previous Jobs"
        field: endDate
        pattern: true
      - label: "Current Jobs"
        field: endDate
        pattern: false
    fields:
      - {
          label: "Company",
          name: "companyName",
          widget: "string",
          required: true,
        }
      - { label: "website", name: "website", widget: "string", required: true }
      - {
          label: "position",
          name: "position",
          widget: "string",
          required: true,
        }
      - {
          label: "Start Date",
          name: "startDate",
          widget: "date",
          required: true,
        }
      - { label: "End Date", name: "endDate", widget: "date" }
      - {
          label: "Languages",
          name: "languages",
          widget: "select",
          multiple: true,
          required: true,
          options: ["javascript", "typescript", "python"],
        }
      - {
          label: "Technologies Used",
          name: "tech",
          widget: "select",
          required: true,
          multiple: true,
          options:
            [
              "python",
              "node",
              "express",
              "javascript",
              "typescript",
              "angular",
              "react",
              "nextjs",
              "gatsby",
              "graphql",
              "react-native",
              "redux",
              "electron",
              "postgres",
              "mongodb",
              "redis",
              "firebase",
              "styled-components",
              "sass",
              "theme-ui",
              "feathers",
              "mobx-state-tree",
              "css3",
              "html5",
              "heroku",
              "aws",
              "azure",
              "netlify",
              "parse",
              "sequelize",
              "serverless",
              "mongoose",
              "docker",
              "socketio",
            ],
        }
      - { label: "Summary", name: "body", widget: "markdown" }
