backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/
public_folder: /
logo_url: https://estep.nyc/logo/full-logo.svg
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "blog"
    extension: mdx
    format: frontmatter
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    extension: mdx
    format: frontmatter
    label: "Projects"
    label_singular: "Project"
    folder: "src/content/projects"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Display size",
          name: "size",
          widget: "select",
          default: "normal",
          multiple: false,
          options: ["normal", "small"],
          required: true,
        }
      - { label: "Publish Date", name: "date", widget: "date", required: true }
      - {
          label: "Banners",
          name: "banners",
          widget: "list",
          options: ["hackathon"],
          multiple: true,
          required: false,
        }
      - {
          label: "Technologies Used",
          name: "tech",
          widget: "select",
          required: true,
          multiple: true,
          options:
            [
              "python",
              "node",
              "express",
              "javascript",
              "typescript",
              "angular",
              "react",
              "nextjs",
              "gatsby",
              "graphql",
              "react-native",
              "redux",
              "electron",
              "postgres",
              "mongodb",
              "redis",
              "firebase",
              "styled-components",
              "sass",
              "theme-ui",
              "feathers",
              "mobx-state-tree",
              "css3",
              "html5",
              "heroku",
              "aws",
              "azure",
              "netlify",
              "parse",
              "sequelize",
              "serverless",
              "mongoose",
              "docker",
              "socketio",
            ],
        }
      - {
          label: "Languages",
          name: "languages",
          widget: "select",
          multiple: true,
          required: true,
          options: ["javascript", "typescript", "python"],
        }
      - { label: "Images", name: "images", widget: "file" }
      - { label: "Git Repository URL", name: "repo", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - name: "work"
    label: "Work Experience"
    folder: "src/content/work"
    extension: mdx
    format: frontmatter
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{companyName}}"
    editor:
      preview: false
    fields:
      - {
          label: "Company",
          name: "companyName",
          widget: "string",
          required: true,
        }
      - { label: "website", name: "website", widget: "string", required: true }
      - {
          label: "position",
          name: "position",
          widget: "string",
          required: true,
        }
      - { label: "Start Date", name: "startDate", widget: "date" }
      - { label: "End Date", name: "endDate", widget: "date" }
      - { label: "companyName", name: "body", widget: "markdown" }
      - {
          label: "Technologies Used",
          name: "tech",
          widget: "select",
          required: true,
          multiple: true,
          options:
            [
              "python",
              "node",
              "express",
              "javascript",
              "typescript",
              "angular",
              "react",
              "nextjs",
              "gatsby",
              "graphql",
              "react-native",
              "redux",
              "electron",
              "postgres",
              "mongodb",
              "redis",
              "firebase",
              "styled-components",
              "sass",
              "theme-ui",
              "feathers",
              "mobx-state-tree",
              "css3",
              "html5",
              "heroku",
              "aws",
              "azure",
              "netlify",
              "parse",
              "sequelize",
              "serverless",
              "mongoose",
              "docker",
              "socketio",
            ],
        }
      - {
          label: "Languages",
          name: "languages",
          widget: "select",
          multiple: true,
          required: true,
          options: ["javascript", "typescript", "python"],
        }
